name: publish_conda

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: s-weigand/setup-conda@v1
    - name: publish-to-conda
      uses: fcakyon/conda-package-publish-action@master
      with:
        subdir: 'conda'
        anacondatoken: ${{ secrets.ANACONDA_TOKEN }}
        platforms: 'oxs linux'
        
