# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build Master Docs

on: 
  push:
    branches: [ master ]

jobs:
  docs:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1
        
      - name: Set up Python
        uses: actions/github-script@0.3.0
        with:
          github-token: ${{github.token}}
          script: |
            const core = require('@actions/core')
            core.exportVariable("PATH", "/home/ubuntu/anaconda3/bin:/usr/local/bin:/usr/bin/:/bin:$PATH")
                      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy -I
          pip install pytest torch
          
      - name: Install package
        run: |
          pip install -e .
          
      - name: Install Sphix Dependencies
        run: |
          cd docs/
          pip install -r requirements.txt
          
      - name: Build Sphinx docs
        run: |
          cd docs/
          make html
          touch build/html/.nojekyll
          touch build/html/CNAME
          echo "autotorch.org" >> build/html/CNAME
          mkdir -p build/html/.well-known
          mkdir -p build/html/.well-known/pki-validation
          cp source/_static/*.txt build/html/.well-known/pki-validation
          cp ./build/html/_downloads/**/*.ipynb ./build/html/_downloads/
          cd ..
          
      # https://github.com/marketplace/actions/github-pages
      - name: Deploy
        if: success()
        uses: crazy-max/ghaction-github-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          build_dir: docs/build/html/
          target_branch: gh-pages
